---
secrets_file: ./.secrets.yml

userdata:
  sensu:
    host: sensu_server
    port: 4567

stacks:
  - name: sensu
    units:
      - name: bare
        version: 1.0.0
        dockerfile: ./_bare/Dockerfile
        startable: false

      - name: base
        version: 1.0.0
        dockerfile: ./_base/Dockerfile
        startable: false
        needed_unit_names:
          - bare

      - name: redis
        version: 1.0.0
        dockerfile: ./redis/Dockerfile
        needed_unit_names:
          - bare
        env:
          - SERVICE_NAME=redis
          - SERVICE_TAGS=sensu

      - name: rabbitmq
        version: 1.0.0
        dockerfile: ./rabbitmq/Dockerfile
        # ports:
        #   - "5671:5671"
        #   - "15672:15672"
        needed_unit_names:
          - bare
        volumes:
          - /data/sensu-rabbitmq/logs:/var/log
        env:
          - SERVICE_NAME=rabbitmq
          - SERVICE_TAGS=sensu

      - name: server
        version: 1.0.0
        dockerfile: ./server/Dockerfile
        # ports:
        #   - "4567:4567"
        needed_unit_names:
          - bare
          - base
          - redis
          - rabbitmq
        volumes:
          - /data/sensu-server/logs:/var/log
        env:
          - ENABLE_ALERTS=false
          - SERVICE_NAME=server
          - SERVICE_TAGS=sensu

      - name: client
        version: 1.0.0
        dockerfile: ./client/Dockerfile
        needed_unit_names:
          - bare
          - base
          - rabbitmq
        volumes:
          - /data/sensu-client/logs:/var/log
        env:
          - SERVICE_NAME=client
          - SERVICE_TAGS=sensu

      - name: dashboard
        docker_image: uchiwa/uchiwa:latest
        version: 1.0.0
        # ports:
        #   - "3000:3000"
        volumes:
          - /data/sensu-dashboard/logs:/var/log
          - /docker/percheron-sensu/dashboard/config:/config
        needed_unit_names:
          - server
        env:
          - SERVICE_NAME=dashboard
          - SERVICE_TAGS=sensu
