---
secrets_file: ./.secrets.yml

userdata:
  rabbitmq:
    host: rabbitmq.apps.mine.nu
    port: 5671

stacks:
  - name: sensu
    units:
      - name: bare
        version: 1.0.0
        dockerfile: ./_bare/Dockerfile
        startable: false

      - name: base
        version: 1.0.0
        dockerfile: ./_base/Dockerfile
        startable: false
        needed_unit_names:
          - bare

      - name: client
        version: 1.0.0
        dockerfile: ./client/Dockerfile
        hostname: rebellion_client
        needed_unit_names:
          - bare
          - base
        volumes:
          - /data/sensu-client/logs:/var/log
        env:
          - SERVICE_NAME=client
          - SERVICE_TAGS=sensu

