---
docker:
  host: "tcp://192.168.99.100:2376"

stacks:
  - name: sensu
    units:
      - name: bare
        version: 1.0.0
        dockerfile: ./_bare/Dockerfile
        startable: false

      - name: base
        version: 1.0.0
        dockerfile: ./_base/Dockerfile
        startable: false
        dependant_unit_names:
          - bare

      - name: redis
        version: 1.0.0
        dockerfile: ./redis/Dockerfile
        ports:
          - "6379:6379"
        dependant_unit_names:
          - bare

      - name: rabbitmq
        version: 1.0.0
        dockerfile: ./rabbitmq/Dockerfile
        ports:
          - "5671:5671"
          - "15672:15672"
        dependant_unit_names:
          - bare

      - name: server
        version: 1.0.0
        dockerfile: ./server/Dockerfile
        ports:
          - "4567:4567"
        dependant_unit_names:
          - bare
          - base
          - redis
          - rabbitmq

      - name: client
        version: 1.0.1
        dockerfile: ./client/Dockerfile
        dependant_unit_names:
          - bare
          - base
          - rabbitmq

      - name: dashboard
        docker_image: uchiwa/uchiwa:latest
        version: 1.0.0
        ports:
          - "3000:3000"
        volumes:
          - "/Users/ash/src/percheron/sensu/dashboard/config:/config"
        dependant_unit_names:
          - server
