#!/bin/sh

sed -i "s%<NODE_NAME>%${HOSTNAME}%" /etc/sensu/config.json
sed -i "s%<NODE_IP>%$(curl ifconfig.co)%" /etc/sensu/config.json

mkdir -p /var/log/sensu

/usr/bin/supervisord -n -c /etc/supervisord.conf
